game.resources = [
    {name: "bg", type:"image", src: "data/img/office_bg_2.png"},
    {name: "player", type: "image", src: "data/img/plane_static.png" },
    {name: "clumsy", type:"image", src: "data/img/plane_static.png"},
    {name: "pipe", type:"image", src: "data/img/pipe.png"},
    {name: "ground", type:"image", src: "data/img/ground.png"},
    {name: "gameover", type:"image", src: "data/img/gameover.png"},
    {name: "gameoverbg", type:"image", src: "data/img/score_container_2.png"},
    {name: "hit", type:"image", src: "data/img/hit.png"},
    {name: "getready", type:"image", src: "data/img/getready.png"},
    {name: "grumpybird", type:"image", src: "data/img/grumpybird.png"},
    {name: "light", type:"image", src: "data/img/office_assets_light.png"},
    {name: "cabinet", type:"image", src: "data/img/office_assets_kiwi_cabinet.png"},
    {name: "desk_sml", type:"image", src: "data/img/desk-sml-2.png"},
    {name: "desk_lrg", type:"image", src: "data/img/desk-lrg-2.png"},
    {name: "try_again", type: "image", src: "data/img/try_again_button.png"},
    {name: "enter_comp_button", type: "image", src: "data/img/enter_comp_button.png"},
    {name: "best_score_background", type: "image", src: "data/img/best_score_button_container.png"},
    {name: "shapesdef", type:"json", src: "data/json/kiwi_trace.json"}
];
